- name: configure firewall
  hosts: all
  become: yes
  become_user: root

  vars:

    firewall_allowed_tcp_ports:
      - "22"   # ssh
      - "80"   # http
      - "2222" # ssh for vagrant
      - "8000" # test server port
    firewall_allowed_udp_ports: []

  roles:

    - name: setup firewall
      role: geerlingguy.firewall
