
- name: install packages
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: add repository for newer python packages
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: setup basic packages
      apt: name={{item}} state=present
      with_items:
        - emacs
        - "{{tt_python}}"
        - "{{tt_python}}-dev"
        - "{{tt_python}}-venv"
        - supervisor
        - libffi-dev
        - g++
        - libssl-dev
        - screen
        - unzip

    - name: start supervisor
      raw: systemctl start supervisor
