
- name: configure hosts
  hosts: all
  become: yes
  become_user: root
  tasks:
    - lineinfile:
        dest: /etc/hosts
        regexp: "{{item[0]}} {{item[1]}}"
        line: "{{item[0]}} {{item[1]}}"
      with_nested:
        - "{{ansible_all_ipv4_addresses}}"
        - ["{{tt_domain}}", "temp-informer.{{tt_domain}}", "informer.{{tt_domain}}"]


- name: setup nginx
  hosts: all
  become: yes
  become_user: root

  roles:

    - name: configure nginx
      role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_client_max_body_size: "1m"
      nginx_vhosts: []


- name: configure nginx
  hosts: all
  become: yes
  become_user: root
  tasks:

    - name: "install configs"
      template:
        src: ../templates/nginx-site.conf
        dest: "/etc/nginx/sites-enabled/the_tale.conf"
        mode: 0644
        owner: "root"
        group: "root"

    - name: "install configs"
      template:
        src: ../templates/uwsgi_params
        dest: "/etc/nginx/uwsgi_params"
        mode: 0644
        owner: "root"
        group: "root"


    - service: name=nginx state=restarted