- name: configure redis
  hosts: all
  become: yes
  become_user: root

  vars:

    redis_unixsocket: /var/run/redis/redis.sock
    redis_timeout: 0
    redis_save: []
    redis_maxmemory: 0
    redis_appendfsync: "no"

  roles:

    - name: configure redis
      role: geerlingguy.redis


- name: change redis socket permissions
  hosts: all
  become: yes
  become_user: root
  tasks:

    - lineinfile:
        dest: /etc/redis/redis.conf
        regexp: "unixsocketperm"
        line: "unixsocketperm 777"

    - service: name=redis-server state=restarted