- name: "preinstall {{name}}"
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: TT soft currency rollback cron
      cron:
        name: soft currency rollback
        cron_file: tt_soft_currency_rollback
        minute: 0
        user: tt_soft_currency
        job: /home/tt_soft_currency/current/venv/bin/tt_bank_rollback_hanged_transactions -c /etc/tt_soft_currency/config.json

    - name: TT soft currency remove old transactions
      cron:
        name: soft currency rollback
        cron_file: tt_soft_currency_remove_old
        minute: 0
        user: tt_soft_currency
        job: /home/tt_soft_currency/current/venv/bin/tt_bank_remove_old_transactions -c /etc/tt_soft_currency/config.json -t 86400

    - name: The Tale clans statistics sync
      cron:
        name: clans statistics sync
        cron_file: the_tale_clans_sync_statistics
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clans_sync_statistics --settings the_tale.settings

    - name: The Tale clans points adding
      cron:
        name: clans points adding
        cron_file: the_tale_clans_pints_adding
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clans_give_points --interval 3600 --settings the_tale.settings

    - name: TT clans currencies rollback cron
      cron:
        name: clans currencies rollback
        cron_file: tt_clans_currencies_rollback
        minute: 0
        user: tt_clans_currencies
        job: /home/tt_clans_currencies/current/venv/bin/tt_bank_rollback_hanged_transactions -c /etc/tt_clans_currencies/config.json

    - name: The Tale clans free quests reset
      cron:
        name: clans free quests reset
        cron_file: the_tale_clans_reset_free_quests
        minute: 0
        hour: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin clans_reset_free_quests --settings the_tale.settings

    - name: The Tale emissaries step
      cron:
        name: emissaries step
        cron_file: the_tale_emissaries_step
        minute: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin emissaries_step --settings the_tale.settings

    - name: The Tale emissaries monitoring
      cron:
        name: emissaries monitoring
        cron_file: the_tale_emissaries_monitoring
        # 30 минута исключена, так как в это время обрабатываются суточные эффекты
        # 00 минута исключена, так как в это время обрабатываются часовые эффекты
        minute: 5,10,15,20,25,35,40,45,50,55
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin emissaries_monitoring --settings the_tale.settings

    - name: The Tale emissaries days cycle
      cron:
        name: process emissaries days cycle
        cron_file: the_tale_emissaries_process_day
        minute: 30
        hour: 0
        user: the_tale
        job: /home/the_tale/current/venv/bin/django-admin emissaries_process_day --settings the_tale.settings
