- name: install The Tale
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: The Tale
    user: the_tale
    packages: "{{tt_services['the_tale']['packages']}}"
    django_settings: the_tale.settings
    port: 10000
    collect_static: true


- name: install TT Diary
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: TT Diary
    user: tt_diary
    packages: "{{tt_services['tt_diary']['packages']}}"
    django_settings: tt_diary.settings
    port: 10001
    collect_static: false


- name: install TT Personal Messages
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: TT Personal Messages
    user: tt_personal_messages
    packages: "{{tt_services['tt_personal_messages']['packages']}}"
    django_settings: tt_personal_messages.settings
    port: 10002
    collect_static: false


- name: install TT Storage
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: TT Storage
    user: tt_storage
    packages: "{{tt_services['tt_storage']['packages']}}"
    django_settings: tt_storage.settings
    port: 10003
    collect_static: false


- name: install TT Market
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: TT Market
    user: tt_market
    packages: "{{tt_services['tt_market']['packages']}}"
    django_settings: tt_market.settings
    port: 10004
    collect_static: false


- name: install TT soft currency
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: TT soft currency
    user: tt_soft_currency
    packages: "{{tt_services['tt_soft_currency']['packages']}}"
    django_settings: tt_bank.settings
    port: 10005
    collect_static: false


- name: install TT players timers
  import_playbook: ../tasks/tt_service.yml
  vars:
    name: TT players timers
    user: tt_players_timers
    packages: "{{tt_services['tt_players_timers']['packages']}}"
    django_settings: tt_timers.settings
    port: 10006
    collect_static: false


- name: install services cron files
  import_playbook: ../tasks/tt_cron.yml


- name: The Tale postupdate operations
  hosts: all
  become: yes
  become_user: the_tale
  tasks:

    - name: create world
      raw: cd /home/the_tale/current && . /home/the_tale/current/venv/bin/activate && django-admin game_create_world --settings the_tale.settings

    - name: create superuser
      raw: "cd /home/the_tale/current && . /home/the_tale/current/venv/bin/activate && django-admin accounts_create_superuser --settings the_tale.settings"

    - name: sync data
      raw: cd /home/the_tale/current && . /home/the_tale/current/venv/bin/activate && django-admin portal_postupdate_operations --settings the_tale.settings


- name: host postupdate operations
  hosts: all
  become: yes
  become_user: root
  tasks:

    - name: install the_tale supervisor configs
      template: src="../templates/the-tale-supervisor.conf" dest="/etc/supervisor/conf.d/the_tale.conf"

    - name: reload supervisor configs
      raw: systemctl restart supervisor

    - name: "install authorized keys"
      authorized_key:
        user: root
        key: "{{item}}"
      with_items: "{{tt_authorized_keys}}"
