version: "3.9"

volumes:
  postgresql-storage: {}
  postgresql-backups: {}


services:

  # TODO
  core-postgresql:
    volumes:
       - postgresql-storage:/var/lib/postgresql/data

  # TODO
  utils-postgresql:
    volumes:
       - postgresql-backups:/backups/

  # TODO
  core-nginx:
    environment:
      TT_SERVERS: "site xsolla localhost temp_informer"
      # TODO
      TT_GENERATE_CERTIFICATES: "yes"

  core-postfix:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postfix:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/postfix/config.$TT_ENV.json:/root/postfix_config.json:ro

    labels:
      org.the-tale.group: core

    ports:
      - "25"

    networks:
      tt_network: {}

  site:

    depends_on:
      - utils-site-generate-static
