version: "3.9"

volumes:
  postgresql-storage: {}


services:

  # TODO
  core-postgresql:
    environment:
      POSTGRES_PASSWORD: postgresql
    volumes:
       - postgresql-storage:/var/lib/postgresql/data

  # TODO
  utils-backup:

    environment:
      BACKUP_USER: postgres
      BACKUP_PASSWORD: postgresql

    volumes:
       - ${PWD}/.backups:/backups/

  # TODO
  core-nginx:
    environment:
      TT_SERVERS: "site"
      TT_GENERATE_CERTIFICATES: "yes"


  core-postfix:

    image: the-tale/core-postfix:$TT_RELEASE_VERSION

    profiles:
      - core

    volumes:
      - $TT_CONFIGS_ROOT/postfix/config.$TT_ENV.json:/root/postfix_config.json:ro

    ports:
      - "25"

  # TODO: uncomment
  # site:

  #   depends_on:
  #     - utils-site-generate-static

  # TODO: remove

  utils-site-generate-static:
    volumes:
      - ${PWD}:/home/tt_service/repository

  site:
    volumes:
      - ${PWD}:/home/tt_service/repository

  utils-site-migrations:
    volumes:
      - ${PWD}:/home/tt_service/repository

  utils-site:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-bank-processor:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-xsolla-banker:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-refrigerator:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-message-sender:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-items-manager:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-linguistics-manager:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-achievements-manager:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-turns-loop:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-logic-1:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-logic-2:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-quests-generator:
    volumes:
      - ${PWD}:/home/tt_service/repository

  worker-supervisor:
    volumes:
      - ${PWD}:/home/tt_service/repository
