version: "3.9"

volumes:
  postgresql-storage: {}


services:

  core-postgresql:
    environment:
      POSTGRES_PASSWORD: postgresql
    volumes:
       - postgresql-storage:/var/lib/postgresql/data

  utils-backup:

    environment:
      BACKUP_USER: postgres
      BACKUP_PASSWORD: postgresql

  core-nginx:
    environment:
      TT_SERVERS: "site"
      TT_GENERATE_CERTIFICATES: "yes"
