# define services sceletons with help of yaml templating

version: "3.9"

x-core:
  &default-core

  labels:
    org.the-tale.group: core
    com.datadoghq.tags.env: $TT_ENV
    com.datadoghq.tags.version: $TT_VERSION

  stop_grace_period: 1m

  profiles:
    - core

  networks:
    tt_network: {}


x-utils:
  &default-utils

  stop_grace_period: 1m

  labels:
    org.the-tale.group: utils
    com.datadoghq.tags.env: $TT_ENV
    com.datadoghq.tags.version: $TT_VERSION

  environment:
    TT_WAIT_TIMEOUT: $TT_WAIT_TIMEOUT
    TT_SITE_STATIC_DIR: $TT_SITE_STATIC_DIR

  networks:
    tt_network: {}

  profiles:
    - utils

x-tt-service:
  &default-tt-service

  labels:
    org.the-tale.group: services

  command: tt_run_service

  stop_grace_period: 1s

  environment:
    TT_WAIT_TIMEOUT: $TT_WAIT_TIMEOUT

  profiles:
    - services

  networks:
    tt_network: {}

x-the-tale:
  &default-the-tale

  stop_grace_period: 1s

  environment:
    TT_WAIT_TIMEOUT: $TT_WAIT_TIMEOUT
    TT_SITE_STATIC_DIR: $TT_SITE_STATIC_DIR

  image: $TT_CONTAINERS_REGISTRY/the-tale/site:$TT_RELEASE_VERSION

  volumes:
    # all site containers must has access to static files foulder
    # they determine maintenance mode with its help
    - tt_site_static:/var/www/site/
    - $TT_CONFIGS_ROOT/the_tale/settings_local.py:/home/tt_service/repository/src/the_tale/the_tale/settings_local.py

  networks:
    tt_network: {}

x-the-tale-worker:
  &default-the-tale-worker
  << : *default-the-tale

  command: tt_worker

  stop_grace_period: 10s

  profiles:
    - workers

  labels:
    org.the-tale.group: workers

  depends_on:
    - utils-site-migrations


networks:
  tt_network:
    driver: bridge


volumes:
  tt_nginx_sertificates: {}
  tt_site_static: {}


services:

  core-postgresql:
    << : *default-core

  core-redis:
    << : *default-core

  core-rabbitmq:
    << : *default-core

  core-nginx:
    << : *default-core

  core-postfix:
    << : *default-core

  core-datadog:
    << : *default-core

  utils-postgresql:
    << : *default-utils

  utils-certbot:
    << : *default-utils

  utils-site-migrations:
    << : *default-utils

  utils-site:
    << : *default-utils

  utils-site-generate-static:
    << : *default-utils

  utils-regenerate-protocol:
    << : *default-utils

  tt-diary:
    << : *default-tt-service

  tt-personal-messages:
    << : *default-tt-service

  tt-storage:
    << : *default-tt-service

  tt-market:
    << : *default-tt-service

  tt-players-timers:
    << : *default-tt-service

  tt-personal-impacts:
    << : *default-tt-service

  tt-crowd-impacts:
    << : *default-tt-service

  tt-job-impacts:
    << : *default-tt-service

  tt-fame-impacts:
    << : *default-tt-service

  tt-game-chronicle:
    << : *default-tt-service

  tt-clans-chronicle:
    << : *default-tt-service

  tt-money-spendings:
    << : *default-tt-service

  tt-emissaries-impacts:
    << : *default-tt-service

  tt-players-properties:
    << : *default-tt-service

  tt-clans-properties:
    << : *default-tt-service

  tt-matchmaker:
    << : *default-tt-service

  tt-places-effects:
    << : *default-tt-service

  tt-clans-currencies:
    << : *default-tt-service

  tt-emissaries-events-currencies:
    << : *default-tt-service

  tt-emissaries-events-uniquer:
    << : *default-tt-service

  tt-discord:
    << : *default-tt-service

  tt-data-protector:
    << : *default-tt-service

  tt-xsolla:
    << : *default-tt-service

  site:
    << : *default-the-tale

  worker-bank-processor:
    << : *default-the-tale-worker

  worker-xsolla-banker:
    << : *default-the-tale-worker

  worker-refrigerator:
    << : *default-the-tale-worker

  worker-message-sender:
    << : *default-the-tale-worker

  worker-items-manager:
    << : *default-the-tale-worker

  worker-linguistics-manager:
    << : *default-the-tale-worker

  worker-achievements-manager:
    << : *default-the-tale-worker

  worker-turns-loop:
    << : *default-the-tale-worker

  worker-logic-1:
    << : *default-the-tale-worker

  worker-logic-2:
    << : *default-the-tale-worker

  worker-quests-generator:
    << : *default-the-tale-worker

  worker-supervisor:
    << : *default-the-tale-worker
