version: "3.9"

volumes:
  postgresql-storage: {}
  postgresql-backups: {}


services:

  core-postgresql:
    volumes:
       - postgresql-storage:/var/lib/postgresql/data

  utils-postgresql:
    volumes:
       - postgresql-backups:/backups/

  core-postfix:
    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postfix:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/postfix/config.$TT_ENV.json:/root/postfix_config.json:ro

    labels:
      org.the-tale.group: core
      com.datadoghq.tags.env: $TT_ENV
      com.datadoghq.tags.service: core-postfix
      com.datadoghq.tags.version: $TT_VERSION

    ports:
      - "25:25"

    networks:
      tt_network: {}

  core-datadog:

    image: gcr.io/datadoghq/agent:7

    environment:
      DD_API_KEY: $TT_DATADOG_API_KEY

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - $TT_CONFIGS_ROOT/datadog/conf.d:/conf.d:ro

    networks:
      tt_network: {}

  site:

    depends_on:
      - utils-site-generate-static
