version: "3.9"

networks:
  tt_network:
    driver: bridge


volumes:
  tt_site_static: {}
  tt_certbot_well_known: {}
  tt_certbot_storage: {}

services:

  core-postgresql:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-postgresql:$TT_RELEASE_VERSION

    volumes:
       - $TT_CONFIGS_ROOT/postgresql/postgresql.$TT_ENV.conf:/etc/postgresql/postgresql.conf:ro

    stop_grace_period: 1m

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $TT_DB_ROOT_PASSWORD

    labels:
      org.the-tale.group: core
      com.datadoghq.tags.env: $TT_ENV
      com.datadoghq.tags.service: core-postgresql
      com.datadoghq.tags.version: $TT_VERSION

    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

    networks:
      tt_network: {}

  utils-postgresql:

    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-postgresql:$TT_RELEASE_VERSION

    volumes:
       - $TT_CONFIGS_ROOT/utils_postgresql/aws.config:/root/aws.config:ro

    stop_grace_period: 1m

    labels:
      org.the-tale.group: utils

    environment:
      TT_DATABASES: $TT_DATABASES
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $TT_DB_ROOT_PASSWORD
      TT_S3_BACKET: $TT_BACKUP_S3_BACKET
      TT_DATADOG_POSTGRESQL_USER: $TT_DATADOG_POSTGRESQL_USER
      TT_DATADOG_POSTGRESQL_PASSWORD: $TT_DATADOG_POSTGRESQL_PASSWORD

    depends_on:
      - core-postgresql

    networks:
      tt_network: {}

    profiles:
      - utils

  core-redis:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-redis:$TT_RELEASE_VERSION

    stop_grace_period: 1m

    labels:
      org.the-tale.group: core
      com.datadoghq.tags.env: $TT_ENV
      com.datadoghq.tags.service: core-redis
      com.datadoghq.tags.version: $TT_VERSION

    networks:
      tt_network: {}

  core-rabbitmq:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-rabbitmq:$TT_RELEASE_VERSION

    stop_grace_period: 1m

    volumes:
       - $TT_CONFIGS_ROOT/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

    labels:
      org.the-tale.group: core
      com.datadoghq.tags.env: $TT_ENV
      com.datadoghq.tags.service: core-rabbitmq
      com.datadoghq.tags.version: $TT_VERSION

    networks:
      tt_network: {}

  core-nginx:

    image: $TT_CONTAINERS_REGISTRY/the-tale/core-nginx:$TT_RELEASE_VERSION

    environment:
      TT_SERVERS: $TT_SERVERS
      TT_DOMAINS: $TT_DOMAINS

    stop_grace_period: 1s

    labels:
      org.the-tale.group: core
      com.datadoghq.tags.env: $TT_ENV
      com.datadoghq.tags.service: core-nginx
      com.datadoghq.tags.version: $TT_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/nginx/config.$TT_ENV.json:/root/nginx_config.json:ro
      - tt_certbot_well_known:/var/www/certbot/:ro
      - tt_certbot_storage:/etc/letsencrypt/:ro
      - tt_site_static:/var/www/site/:ro

    ports:
      - "80:80"
      - "443:443"

    networks:
      tt_network: {}

  # https://mindsers.blog/post/https-using-nginx-certbot-docker/
  utils-certbot:

    image: $TT_CONTAINERS_REGISTRY/the-tale/utils-certbot:$TT_RELEASE_VERSION

    labels:
      org.the-tale.group: utils

    environment:
      TT_DOMAINS: $TT_DOMAINS

    volumes:
      - tt_certbot_well_known:/var/www/certbot/
      - tt_certbot_storage:/etc/letsencrypt/
      - $TT_CONFIGS_ROOT/utils_certbot/cli.ini:/etc/letsencrypt/cli.ini:ro

    profiles:
      - utils

  tt-diary:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-diary:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_diary/config.json:/home/tt_service/config.json

  tt-personal-messages:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-personal-messages:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_personal_messages/config.json:/home/tt_service/config.json

  tt-storage:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-storage:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_storage/config.json:/home/tt_service/config.json

  tt-market:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-market:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_market/config.json:/home/tt_service/config.json

  tt-players-timers:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-timers:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_players_timers/config.json:/home/tt_service/config.json

  tt-personal-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_personal_impacts/config.json:/home/tt_service/config.json

  tt-crowd-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_crowd_impacts/config.json:/home/tt_service/config.json

  tt-job-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_job_impacts/config.json:/home/tt_service/config.json

  tt-fame-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_fame_impacts/config.json:/home/tt_service/config.json

  tt-game-chronicle:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-events-log:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_game_chronicle/config.json:/home/tt_service/config.json

  tt-clans-chronicle:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-events-log:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_clans_chronicle/config.json:/home/tt_service/config.json

  tt-money-spendings:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_money_spendings/config.json:/home/tt_service/config.json

  tt-emissaries-impacts:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-impacts:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_impacts/config.json:/home/tt_service/config.json

  tt-players-properties:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-properties:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_players_properties/config.json:/home/tt_service/config.json

  tt-clans-properties:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-properties:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_clans_properties/config.json:/home/tt_service/config.json

  tt-matchmaker:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-matchmaker:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_matchmaker/config.json:/home/tt_service/config.json

  tt-places-effects:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-effects:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_places_effects/config.json:/home/tt_service/config.json

  tt-clans-currencies:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-bank:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_clans_currencies/config.json:/home/tt_service/config.json

  tt-emissaries-events-currencies:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-bank:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_events_currencies/config.json:/home/tt_service/config.json

  tt-emissaries-events-uniquer:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-uniquer:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_emissaries_events_uniquer/config.json:/home/tt_service/config.json

  tt-discord:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-discord:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_discord/config.json:/home/tt_service/config.json

  tt-data-protector:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-data-protector:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_data_protector/config.json:/home/tt_service/config.json

  tt-xsolla:
    image: $TT_CONTAINERS_REGISTRY/the-tale/tt-xsolla:$TT_RELEASE_VERSION

    volumes:
      - $TT_CONFIGS_ROOT/tt_xsolla/config.json:/home/tt_service/config.json

  utils-site-migrations:
    labels:
      org.the-tale.group: utils

    profiles:
      - utils
      - workers
      - site

    command: tt_django migrate

  site:
    command: tt_site -b 0.0.0.0:80 -w 4

    profiles:
      - site

    labels:
      org.the-tale.group: site

  utils-site:
    profiles:
      - utils

    labels:
      org.the-tale.group: utils

  utils-site-generate-static:
    profiles:
      - utils

    command: tt_generate_static

    labels:
      org.the-tale.group: utils

  worker-bank-processor:
    environment:
      TT_WORKER: bank_processor

  worker-xsolla-banker:
    environment:
      TT_WORKER: xsolla_banker

  worker-refrigerator:
    environment:
      TT_WORKER: refrigerator

  worker-message-sender:
    environment:
      TT_WORKER: message_sender

  worker-items-manager:
    environment:
      TT_WORKER: items_manager

  worker-linguistics-manager:
    environment:
      TT_WORKER: linguistics_manager

  worker-achievements-manager:
    environment:
      TT_WORKER: achievements_manager

    depends_on:
      - worker-items-manager

  worker-turns-loop:
    environment:
      TT_WORKER: turns_loop

  worker-logic-1:
    environment:
      TT_WORKER: logic_1

    # service can be stopped only by worker_supervisor
    stop_grace_period: 8760h

  worker-logic-2:
    environment:
      TT_WORKER: logic_2

    # service can be stopped only by worker_supervisor
    stop_grace_period: 8760h

  worker-quests-generator:
    environment:
      TT_WORKER: quests_generator

  worker-supervisor:
    environment:
      TT_WORKER: supervisor

    stop_grace_period: 1h

    depends_on:
      - worker-logic-1
      - worker-logic-2
