
- name: Ensure tt services configs directories exists
  file:
    dest: "{{current_configs_docker}}/{{item}}"
    state: directory
  loop: "{{tt_services_configs.keys()}}"


- name: Render tt service configs
  template:
    src: ../templates/json.j2
    dest: "{{current_configs_docker}}/{{item}}/config.json"
  loop: "{{tt_services_configs.keys()}}"
  vars:
    tt_service: "{{item}}"
    tt_config: "{{tt_services_configs[item]}}"

    full_json:
      database:
        name: "{{tt_service}}"
        user: "{{tt_service}}"
        password: "{{tt_service}}"
        host: "{{postgresql_host}}"
        port: 5432
        minsize: 2
        maxsize: 5
        timeout: 60
      log:
        level: "{{tt_log_level}}"
      service:
        port: 80
      django: "{{tt_config.get('django', {})}}"
      custom: "{{tt_config.get('custom', {})}}"
